# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aa1b9da5f295e307c76518365efbcf1bde0969a47c7864100315ee8fd387f90bda1378b1c7cbfc9daa0518c766186be3fa65f261f58b2b26ea397e184003daab

test:
  secret_key_base: 6938a6a36ca92c35deb38b191d347e05520b8102513386f7e96293262eadfc73e669e644c8458a71fbf178571209055646eff4982ec410ca57d363701cf25123

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
